[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["deprecated", "derive"] }
xshell = "0.2.6"

[[bin]]
name = "xtask"
path = "src/xtask.rs"
