[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["deprecated", "derive"] }
xshell = "0.2.7"

[[bin]]
name = "xtask"
path = "src/xtask.rs"
